#!/usr/bin/env node
/**
 * Emit public/demo-data.js — the fixture bundle the panel falls back to when
 * no backend answers (i.e. on GitHub Pages).
 *
 * The panel derives its own RunSummary from `records`, so we ship raw records
 * only and never risk the two summarisers disagreeing.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { buildRuns, FIXTURES_DIR } from "../test/fixtures.mjs";

const here = path.dirname(fileURLToPath(import.meta.url));
const pub = path.join(here, "..", "public");
const out = path.join(pub, "demo-data.js");

// Point file artifacts at site-relative copies so the hosted (Pages) panel can
// display the demo images and hydrate the demo md/html without any backend.
const assetsDir = path.join(pub, "assets");
fs.mkdirSync(assetsDir, { recursive: true });
const runs = buildRuns();
for (const run of runs) {
  for (const rec of run.records) {
    for (const a of rec.artifacts || []) {
      if (typeof a.path === "string" && a.path.startsWith(FIXTURES_DIR + path.sep)) {
        const base = path.basename(a.path);
        fs.copyFileSync(a.path, path.join(assetsDir, base));
        a.path = "assets/" + base;
      }
    }
  }
}

const payload = {
  generatedAt: new Date().toISOString(),
  runs,
};

const js =
  "/* Generated by scripts/build-demo.mjs — do not edit by hand. */\n" +
  `window.__REPORT_DEMO__ = ${JSON.stringify(payload)};\n`;

fs.writeFileSync(out, js, "utf8");
const bytes = Buffer.byteLength(js);
console.log(`wrote ${path.relative(process.cwd(), out)} (${payload.runs.length} runs, ${(bytes / 1024).toFixed(1)} kB)`);
