#!/usr/bin/env node
/**
 * Emit public/demo-data.js — the fixture bundle the panel falls back to when
 * no backend answers (i.e. on GitHub Pages).
 *
 * The panel derives its own RunSummary from `records`, so we ship raw records
 * only and never risk the two summarisers disagreeing.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { buildRuns } from "../test/fixtures.mjs";

const here = path.dirname(fileURLToPath(import.meta.url));
const out = path.join(here, "..", "public", "demo-data.js");

const payload = {
  generatedAt: new Date().toISOString(),
  runs: buildRuns(),
};

const js =
  "/* Generated by scripts/build-demo.mjs — do not edit by hand. */\n" +
  `window.__REPORT_DEMO__ = ${JSON.stringify(payload)};\n`;

fs.writeFileSync(out, js, "utf8");
const bytes = Buffer.byteLength(js);
console.log(`wrote ${path.relative(process.cwd(), out)} (${payload.runs.length} runs, ${(bytes / 1024).toFixed(1)} kB)`);
